# This is a basic workflow to help you get started with Actions

name: Scanner on pr (CMD)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push: #branch github.ref
  #  branches: [ "main" ]
  pull_request: #branch github.head_ref
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  # GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  XY_USERNAME: ${{ secrets.XY_USERNAME }}
  XY_PASSWORD: ${{ secrets.XY_PASSWORD }}
  XY_URL: ${{ secrets.XY_URL }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel 
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: '0'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: git log

      # Runs a set of commands using the runners shell 
      - name: Download Xygeni Scanner 
        run: |
          echo Downloading Xygeni Scanner ....
          curl -L https://get.xygeni.io/latest/scanner/install.sh | /bin/bash -s -- -u ${{ env.XY_USERNAME }} -p ${{ env.XY_PASSWORD }} -s ${{ env.XY_URL }} -d ${GITHUB_WORKSPACE}/scanner 
          ls -al
          cat ${GITHUB_WORKSPACE}/scanner/conf/codetampering/ccm/workflow_modification.yml | grep nonTrivialChangeChecker
          cat ${GITHUB_WORKSPACE}/scanner/conf/codetampering/ccm/workflow_modification.yml | grep changeValidationChecker
          sed -i 's/nonTrivialChangeChecker: empty, comments/nonTrivialChangeChecker: /g' ${GITHUB_WORKSPACE}/scanner/conf/codetampering/ccm/workflow_modification.yml
          sed -i 's/changeValidationChecker: pr_reviewed OR (commit_signed AND author_is_admin)/changeValidationChecker: /g' ${GITHUB_WORKSPACE}/scanner/conf/codetampering/ccm/workflow_modification.yml
          
          cat ${GITHUB_WORKSPACE}/scanner/conf/misconfigurations/unprotected_branch.yml | grep enforceAdmins
          sed -i 's/enforceAdmins: false/enforceAdmins: true /g' ${GITHUB_WORKSPACE}/scanner/conf/misconfigurations/unprotected_branch.yml
          

          echo "-------"
          cat ${GITHUB_WORKSPACE}/scanner/conf/codetampering/ccm/workflow_modification.yml | grep nonTrivialChangeChecker
          cat ${GITHUB_WORKSPACE}/scanner/conf/codetampering/ccm/workflow_modification.yml | grep changeValidationChecker
          cat ${GITHUB_WORKSPACE}/scanner/conf/misconfigurations/unprotected_branch.yml | grep enforceAdmins
          cat ${GITHUB_WORKSPACE}/scanner/conf/codetampering/ccm/workflow_modification.yml


      # Runs a set of commands using the runners shell
      - name: Execution Xygeni Scanner (vuln)
        run: |
          echo Executing Xygeni scan ....    
          ${GITHUB_WORKSPACE}/scanner/xygeni scan --never-fail -n GH-${{ github.event.repository.name }}-pr-${{ github.head_ref }}-CMD --dir ${GITHUB_WORKSPACE} -e **/scanner/**
          echo =======
          ls -al ${GITHUB_WORKSPACE}
          echo =======
          ls -al 
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}

          

      
